spotitube-team/SpotiTube

assets/javascript/app.js
Should be enough to experiment with the API. Don't be afraid of the 182 additions, it's mostly comments lol.
=> Spotify OAuth is working. Commented throughout. 

assets/css/style.css, assets/javascript/app.js, index.html
Hello dear friends! Tasks I worked on:
-> Created a login function for the OAuth functionality
-> Added a friendly welcome message to the first modal explaining what our website does.
-> Did some styling in the modal text and login button (just couldn't get the spotify icon to be horizontally aligned to the white text inside the button)
-> Created a second modal that is shown if the user denies the Spotify authentication. This second modal explains that our website needs access to their Spotify account in order to show the playlists
** The only thing with the last item is that, if the user clicks on the login button in the 2nd modal, the page does not go back to the Spotify authentication page (it goes to the index). I added a on click function in the same 'else' statement as the 2nd …
=> login modal updates

assets/javascript/app.js
You'll see now that there are big comment blocks indicating where things should go in the document so that everything stays organized and easy to navigate as the file gets larger. I also removed several of my giant comments from when I added OAuth the other night because I think we all understand how it works at this point. If there are any questions don't hesitate to ask in the slack channel. 
**Please follow the formatting conventions I added**
=> Added some formatting conventions to app.js to keep it looking pretty

assets/css/style.css, assets/javascript/app.js, assets/javascript/sidenav.js, index.html
Playlist show up in side nav. Right now it lists the entire list I need to work on the pagination still. I also need to finish styling it but need some pointers on how it should look. The playlists have data attributes within it that should be enough for Lakayla to do her part.
=> Playlist in side Nav

assets/css/style.css, assets/javascript/app.js, index.html
=> latest update from my branch

assets/javascript/app.js, index.html
Needs more testing but should work for all situations in theory
=> Arrow buttons work

assets/css/style.css, assets/javascript/app.js, index.html
Good morning
I completed the work on displaying the playlist player, showing the selected user playlist's name, number of songs and image, as well as the songs' titles, duration, artist and album. I did a little bit of styling, which can be much improved. This one was a little more complicated for me, but i got it! Thanks!
=> playlist player working

assets/css/style.css, assets/javascript/app.js, index.html
this one is ok to Merge for some reason hmm hmm.... ?
=> One list to rule them all

assets/javascript/app.js, assets/javascript/rank.js, assets/javascript/search.js
- added search.js and rank.js files so html script tags would stop throwing errors
- they are completely useless right now, I just wanted to add them for the future
- I also added back the data-name attribute to the playlists in the side menu. Seems to have gotten deleted at some point
=> added search.js and rank.js files

assets/css/style.css, assets/javascript/app.js, index.html
Hello everyone!
Music player styling almost done. I finished the playlist title, image, total songs and convert button - just need some help to display the artist, album and duration info correctly (horizontally).
I appreciate your feedback, thanks!
=> player styling

assets/css/style.css, assets/javascript/app.js, index.html
Reverts spotitube-team/SpotiTube#38
=> Revert "player styling"

assets/css/style.css, assets/javascript/app.js
Further improved the player styling, it is looking much better! Let me know what else needs to be worked on, and exactly how you want it to look - so we can improve it even more. Cheers =)
=> further player styling

assets/javascript/app.js, assets/javascript/rank.js, assets/javascript/search.js
I haven't written code to move the progress bar yet, so check the console for the finished message before you continue. After it's finished, videosData in app.js will contain an object of the ranked videos. Keys are spotify track IDs.
=> Video search

assets/css/style.css, assets/javascript/app.js
Did I mention I don't like CSS?
=> started streamlining spotify side

assets/css/style.css, assets/javascript/app.js, assets/javascript/rank.js, assets/javascript/search.js
- Changed playlist header area style
- Added material design style to 'convert button' and changed the button's text
- Minor spacing changes to tracks table style and yt grid style
- Fixed a rare bug that caused ranking algorithm to crash if the search algorithm couldn't find any videos for a track
=> Small style changes and bug fixes

README.md, assets/css/style.css, index.html
link for github is up and opens to another page. readme should be done
=> readme is done and so is the bottom side bar

README.md, index.html
Reverts spotitube-team/SpotiTube#69
=> Revert "readme is done and so is the bottom side bar"

README.md, assets/css/style.css, index.html
read me file is good. youtube sliding is gone. link to github is done. no merge conflicts ayy
=> readme file should be good now

assets/css/style.css
Little fix for the scroll bar in small playlists
=> scroll fix for small playlists

assets/css/style.css, assets/javascript/app.js
Couple small things I noticed that must've gotten changed somewhere in bug fixing
=> last minute style fixes
